#pytest -c smokesuite.ini

[pytest]
python_files =
    test_add_new_payee.py
    test_search.py

addopts=
    --junitxml=reports/test_log.xml
    -p no:warnings
    -s
    -v
    --html=reports/report.html
junit_family=legacy
junit_suite_name = smoke